# Generated by Django 3.2.6 on 2021-08-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpuser',
            name='restaurants',
        ),
    ]
