# Generated by Django 3.2.6 on 2021-08-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dish Name')),
                ('veg', models.BooleanField(verbose_name='Veg or not')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('picture', models.ImageField(blank=True, upload_to='images/dishes/', verbose_name='Picture of Dish')),
            ],
        ),
    ]
