# Generated by Django 3.2.6 on 2021-08-08 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartdishorder',
            name='dish',
        ),
        migrations.AddField(
            model_name='cartdishorder',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.dishes'),
        ),
        migrations.RemoveField(
            model_name='dishorder',
            name='dish',
        ),
        migrations.AddField(
            model_name='dishorder',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.dishes'),
        ),
        migrations.DeleteModel(
            name='Eco',
        ),
    ]
