# Generated by Django 3.2.6 on 2021-08-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pictures',
            field=models.ImageField(blank=True, null=True, upload_to='images/restaurant'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/dishes/', verbose_name='Picture of Dish'),
        ),
    ]
