# Generated by Django 3.2.6 on 2021-08-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20210807_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
