# Generated by Django 3.2.6 on 2021-08-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_dishes_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='currency',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='currency',
            field=models.ManyToManyField(to='restaurant.Currency'),
        ),
    ]
