# Generated by Django 3.2.6 on 2021-08-07 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_corpuser_restaurants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0006_auto_20210807_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='dishes',
            name='eta',
            field=models.IntegerField(default=20, verbose_name='ETA to make the dish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.corpuser'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Order ID')),
                ('instruction', models.TextField(blank=True, null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dishes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.dishes')),
            ],
        ),
    ]
